name: adamimic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - tensorboard
  - tqdm
  - numpy
  - seaborn
  - GitPython
  - pydelatin
  - hydra-core
  - pip
  - wandb
  - pip:
    - pyfqmr==0.3.0
    - git+https://github.com/KellerJordan/Muon